version: "3.8"

services:
  postgres:
    image: postgres:16.0
    container_name: llama_gamer_postgres
    restart: always
    environment:
      POSTGRES_DB: llama_gamer_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: "UTC-4"
    ports:
      - 3030:3030
    command: -p 3030
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init.pgsql:/docker-entrypoint-initdb.d/1.sql
      - ./scripts/triggers.pgsql:/docker-entrypoint-initdb.d/2.sql
      - ./scripts/inserts.pgsql:/docker-entrypoint-initdb.d/3.sql

  pgadmin:
    image: dpage/pgadmin4:7.8
    container_name: llama_gamer_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 4040
    ports:
      - 4040:4040
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pgadmin-data:
  postgres-data:
