name: CI/CD_PUSH_MAIN

on:
  push:
    branches:
      - "main"

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  validate-code:
    runs-on: ubuntu-22.04
    name: Install, Build, Check Code, Test and Release

    steps:
      - name: Get the last commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Get bun
        uses: oven-sh/setup-bun@v1

      - name: Install deps
        run: bun install

      - name: Build app
        run: bun run build

      - name: Check code
        run: bun run check:code

      - name: Test
        run: bun run test

      - name: Semantic release
        run: bunx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
